### ISSUE TITLE
Date picker broken after update from 3.1.4 to 3.1.5

### ISSUE THREAD

**Issue by besi** [justinfrench/formtastic#1252]
### Working date picker in version `3.1.4`

I am using a date picker in conjunction with activeadmin:

```ruby
    f.inputs 'Details' do
      # ....
      f.input :published_at, as: :datepicker
    end
```

This produces a date picker like so:
![screen shot 2017-09-20 at 11 13 06](https://user-images.githubusercontent.com/160412/30636187-105c1c82-9df5-11e7-89e4-e65290f960df.png)

### Broken date picker in version `3.1.5`

When I updated to the latest version of `formtastic` (everything else being equal). I get this JS Error in my console:

> TypeError: input.datepicker is not a function. (In 'input.datepicker($.extend(defaults, options))', 'input.datepicker' is undefined)

### Workaround

I am currently stripping down the version of `formtastic` in my Gemfile in order to keep the functionality working:

```ruby
gem 'activeadmin'
gem 'formtastic', '= 3.1.4' # Date picker won't work otherwise
```

# Discussion

I like the `as: :datepicker` for `Date` objects for it's simplicity. I would even suggest, that the following, most basic, input should result in such a date picker.

```ruby
f.input :some_date
```

**Comment by besi** [comment]
See https://stackoverflow.com/questions/16121895/jquery-datepicker-for-simpleform-just-like-in-activeadmin

**Comment by besi** [comment]
Note: If this functionality is no longer supported one option would be to revert to use the gem [simple-form-datepicker](https://github.com/JasonBarnabe/simple-form-datepicker), which would also allow to customise the date  picker (e.g. starting day etc.)

**Comment by mikz** [comment]
@besi formtastic does not provide `datepicker` input type. It provides `date_picker`. 
https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/date_picker_input.rb

`datepicker` is provided by activeadmin https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/datepicker_input.rb


I don't know from where this JS error comes from or how it tries to initialize the jQuery Datepicker, but it is hardly formtastic issue as formtastic does not provide any javascript.

If formtastic changes the html output between versions please provide example of how exactly that changed.

**Comment by besi** [comment]
@mikz Thanks for the heads up.

I can now use the date picker component as desired:

    f.input :published_at, as: :datepicker, datepicker_options: {firstDay: 1}
