### ISSUE TITLE
belongs_to broken in 0.9.8 (working in 0.9.7)

### ISSUE THREAD

**Issue by AntonTrapp** [justinfrench/formtastic#248]
belongs_to generates the wrong method in the following case (since 0.9.8):

class MashModel < ActiveRecord::Base 
  belongs_to  :existing_model, :class_name => 'MashModel' 

working with 0.9.7, with 0.9.8:

ActionView::TemplateError (undefined method `mash_model_id' for 
# MashModel:0x7f86809a8ab8) on ...

= form.input :existing_model, :as => :select, :collection => @last_models, :id => 'id' 

```
formtastic (0.9.8) rails/./lib/formtastic.rb:748:in `select_input' 
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `send' 
formtastic (0.9.8) rails/./lib/formtastic.rb:1186:in `inline_input_for' 
formtastic (0.9.8) rails/./lib/formtastic.rb:105:in `send' 
formtastic (0.9.8) rails/./lib/formtastic.rb:105:in `input' 
formtastic (0.9.8) rails/./lib/formtastic.rb:104:in `map' 
formtastic (0.9.8) rails/./lib/formtastic.rb:104:in `input' 
```
