### ISSUE TITLE
Setting input_class_finder fails in Rails 3.2

### ISSUE THREAD

**Issue by sepastian** [justinfrench/formtastic#1135]
Hello!

I am working on a Rails 3.2.21 application and have updated formtastic to 3.1.3; I followed the [guide to upgrade to 3.1](https://github.com/justinfrench/formtastic/wiki/Upgrading-to-Formtastic-3.1) to get rid of the deprecation warnings.

The initializer is installed and sets `input_class_finder` and `action_class_finder`, as required.

    # config/initializers/formtastic.rb
    Formtastic::FormBuilder.input_class_finder = Formtastic::InputClassFinder
    Formtastic::FormBuilder.action_class_finder = Formtastic::ActionClassFinder

However, when I try to start the rails server, I get an error.

    ~/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-3.2.21/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `eager_load' for #<Rails::Application::Configuration:0x007f2dbc783b60> (NoMethodError)

What is the problem here?

**Comment by justinfrench** [comment]
Hrm, this doesn't *feel* like a Formtastic issue given that error message, but I could be wrong.

1. What other changes were made? Can you definitively isolate this error to a tiny diff that suggests it's purely a Formtastic upgrade issue, or was there other stuff at play?
2. If you comment out the entire formtastic initializer, what happens?
3. Can you gist a full diff and a full stack trace?

**Comment by zefta** [comment]
Hello,

I got the exact same error!

I got this warning
```sh
DEPRECATION WARNING: input_class is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.input_class_finder instead (upgrade guide on wiki: http://bit.ly/1F9QtKc )).
```

Then I ran
```sh
$ rails generate formtastic:install
```

So it added to my formatastic.rb initializer
```sh
Formtastic::FormBuilder.action_class_finder = Formtastic::ActionClassFinder
Formtastic::FormBuilder.input_class_finder = Formtastic::InputClassFinder
```

Then I got
```sh
/home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `eager_load' for #<Rails::Application::Configuration:0x00000008400058> (NoMethodError)
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/namespaced_class_finder.rb:32:in `use_const_defined?'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/namespaced_class_finder.rb:69:in `<class:NamespacedClassFinder>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/namespaced_class_finder.rb:24:in `<module:Formtastic>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/namespaced_class_finder.rb:1:in `<top (required)>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/input_class_finder.rb:7:in `<module:Formtastic>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/formtastic-3.1.3/lib/formtastic/input_class_finder.rb:1:in `<top (required)>'
	from /home/thibault/Code/Ruby/my-project/config/initializers/formtastic.rb:96:in `<top (required)>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/thibault/Code/Ruby/my-project/config/environment.rb:10:in `<top (required)>'
	from /home/thibault/Code/Ruby/my-project/spec/spec_helper.rb:12:in `require'
	from /home/thibault/Code/Ruby/my-project/spec/spec_helper.rb:12:in `block in <top (required)>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/spork-0.9.2/lib/spork.rb:24:in `prefork'
	from /home/thibault/Code/Ruby/my-project/spec/spec_helper.rb:7:in `<top (required)>'
	from /home/thibault/Code/Ruby/my-project/spec/config/initializers/airbrake_spec.rb:1:in `require'
	from /home/thibault/Code/Ruby/my-project/spec/config/initializers/airbrake_spec.rb:1:in `<top (required)>'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
	from /home/thibault/.rvm/gems/ruby-1.9.3-p551@my-project/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

If I comment the two added lines everything work well.

**Comment by sepastian** [comment]
Hi Justin, [here](https://gist.github.com/anonymous/b4624a9bba554805dbd9) is a gist showing the problem.

I created a new Rails 3.2.21 application, added formtastic ~> 3.0 to Gemfile, ran bundle and tried starting `bin/rails s` - which is giving me the error described.

If commenting out the following lines in the formtastic initializer, everything works as expected.

    # config/initializers/formtastic.rb
     96 #Formtastic::FormBuilder.input_class_finder = Formtastic::InputClassFinder
    106 #Formtastic::FormBuilder.action_class_finder = Formtastic::ActionClassFinder

Does `#eager_load` exist at all in Rails < 4?

**Comment by justinfrench** [comment]
@sepastian @zefta thanks for your help!

Could you try patching Formtastic and tell me if this helps? The easiest way would be `bundle open formtastic` but you might want to check out your own copy and bundle it locally:

I think this is the offending method, according to the trace:

```
class NamespacedClassFinder
  # ...
  def self.use_const_defined?
    defined?(Rails) && ::Rails.application && ::Rails.application.config.eager_load
  end
  # ...
end
```

If you patch it to check for `eager_load` first, I'm curious to se if this helps:

```
class NamespacedClassFinder
  # ...
  def self.use_const_defined?
    defined?(Rails) && ::Rails.application && ::Rails.application.config.respond_to?(:eager_load) && ::Rails.application.config.eager_load
  end
  # ...
end
```

cc @mikz who introduced this code and might have some additional thoughts?

**Comment by mikz** [comment]
@justinfrench looks like it was introduced by #1100, but the origin probably was disparity between how old and new code checked for the setting.

For rails 4 it should be `eager_load` and for rails 3 it should be `cache_classes`. Both have different semantics, but it should work.

Looks like it is begging to just be removed and do a benchmark to support that it has no performance impact. In the end the code does almost the same thing.

For short term, just do https://github.com/justinfrench/formtastic/pull/1137#issuecomment-78117866
and for long term I'll clean it up.

**Comment by sepastian** [comment]
Thanks :+1:

**Comment by mikz** [comment]
Fixed by #1137
